version: '3'

services:
  # Web service nest js appilcation
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://db_user:db_password@db:5432/db_dev?schema=spherity
    ports:
      - '3001:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  # Postgres database
  db:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/web/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data: